// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Kick.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BRAIN_MSG_KICK_H_
#define _FAST_DDS_GENERATED_BRAIN_MSG_KICK_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated Kick is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "booster/idl/std_msgs/Header.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(KICK_SOURCE)
#define KICK_DllAPI __declspec(dllexport)
#else
#define KICK_DllAPI __declspec(dllimport)
#endif // KICK_SOURCE
#else
#define KICK_DllAPI
#endif // EPROSIMA_USER_DLL_EXPORT
#else
#define KICK_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}
} // namespace eprosima::fastcdr

namespace brain {

namespace msg {

/*!
 * @brief This class represents the structure Kick defined by the user in the
 * IDL file.
 * @ingroup Kick
 */
class Kick : public eprosima::fastdds::dds::TopicDataType {
public:
    /*!
     * @brief Copy constructor.
     * @param x Reference to the object brain::msg::Kick that will be copied.
     */
    eProsima_user_DllExport Kick(const Kick &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object brain::msg::Kick that will be copied.
     */
    eProsima_user_DllExport Kick(Kick &&x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object brain::msg::Kick that will be copied.
     */
    eProsima_user_DllExport Kick &operator=(const Kick &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object brain::msg::Kick that will be copied.
     */
    eProsima_user_DllExport Kick &operator=(Kick &&x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x brain::msg::Kick object to compare.
     */
    eProsima_user_DllExport bool operator==(const Kick &x) const;

    /*!
     * @brief Comparison operator.
     * @param x brain::msg::Kick object to compare.
     */
    eProsima_user_DllExport bool operator!=(const Kick &x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(const std_msgs::msg::Header &_header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(std_msgs::msg::Header &&_header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::Header &header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::Header &header();

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(double _x);

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport double x() const;

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport double &x();

    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(double _y);

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport double y() const;

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport double &y();

    /*!
     * @brief This function sets a value in member dir
     * @param _dir New value for member dir
     */
    eProsima_user_DllExport void dir(double _dir);

    /*!
     * @brief This function returns the value of member dir
     * @return Value of member dir
     */
    eProsima_user_DllExport double dir() const;

    /*!
     * @brief This function returns a reference to member dir
     * @return Reference to member dir
     */
    eProsima_user_DllExport double &dir();

    /*!
     * @brief This function sets a value in member goal_x
     * @param _goal_x New value for member goal_x
     */
    eProsima_user_DllExport void goal_x(double _goal_x);

    /*!
     * @brief This function returns the value of member goal_x
     * @return Value of member goal_x
     */
    eProsima_user_DllExport double goal_x() const;

    /*!
     * @brief This function returns a reference to member goal_x
     * @return Reference to member goal_x
     */
    eProsima_user_DllExport double &goal_x();

    /*!
     * @brief This function sets a value in member goal_y
     * @param _goal_y New value for member goal_y
     */
    eProsima_user_DllExport void goal_y(double _goal_y);

    /*!
     * @brief This function returns the value of member goal_y
     * @return Value of member goal_y
     */
    eProsima_user_DllExport double goal_y() const;

    /*!
     * @brief This function returns a reference to member goal_y
     * @return Reference to member goal_y
     */
    eProsima_user_DllExport double &goal_y();

    /*!
     * @brief This function sets a value in member robot_theta_to_field
     * @param _robot_theta_to_field New value for member robot_theta_to_field
     */
    eProsima_user_DllExport void robot_theta_to_field(
        double _robot_theta_to_field);

    /*!
     * @brief This function returns the value of member robot_theta_to_field
     * @return Value of member robot_theta_to_field
     */
    eProsima_user_DllExport double robot_theta_to_field() const;

    /*!
     * @brief This function returns a reference to member robot_theta_to_field
     * @return Reference to member robot_theta_to_field
     */
    eProsima_user_DllExport double &robot_theta_to_field();

    /*!
     * @brief This function sets a value in member power
     * @param _power New value for member power
     */
    eProsima_user_DllExport void power(double _power);

    /*!
     * @brief This function returns the value of member power
     * @return Value of member power
     */
    eProsima_user_DllExport double power() const;

    /*!
     * @brief This function returns a reference to member power
     * @return Reference to member power
     */
    eProsima_user_DllExport double &power();

private:
    std_msgs::msg::Header m_header;
    double m_x{0.0};
    double m_y{0.0};
    double m_dir{0.0};
    double m_goal_x{0.0};
    double m_goal_y{0.0};
    double m_robot_theta_to_field{0.0};
    double m_power{0.0};

public:
    typedef Kick type;

    eProsima_user_DllExport Kick();

    eProsima_user_DllExport ~Kick() override;

    eProsima_user_DllExport bool serialize(
        void *data,
        eprosima::fastrtps::rtps::SerializedPayload_t *payload) override {
        return serialize(data, payload,
                         eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
    }

    eProsima_user_DllExport bool serialize(
        void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload,
        eprosima::fastdds::dds::DataRepresentationId_t data_representation)
        override;

    eProsima_user_DllExport bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t *payload,
        void *data) override;

    eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
        void *data) override {
        return getSerializedSizeProvider(
            data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
    }

    eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
        void *data,
        eprosima::fastdds::dds::DataRepresentationId_t data_representation)
        override;

    eProsima_user_DllExport bool getKey(
        void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport void *createData() override;

    eProsima_user_DllExport void deleteData(void *data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override {
        return false;
    }

#endif // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override {
        return false;
    }

    eProsima_user_DllExport inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation)
        const override {
        static_cast<void>(data_representation);
        return false;
    }

#endif // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void *memory) const override {
        static_cast<void>(memory);
        return false;
    }

#endif // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char *m_keyBuffer;
};

}

} // namespace brain::msg

#endif // _FAST_DDS_GENERATED_BRAIN_MSG_KICK_H_
