// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AudioCommon.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOCOMMON_H_
#define _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOCOMMON_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "AudioCommon.h"

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated AudioCommon is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(AUDIOCOMMON_SOURCE)
#define AUDIOCOMMON_DllAPI __declspec(dllexport)
#else
#define AUDIOCOMMON_DllAPI __declspec(dllimport)
#endif  // AUDIOCOMMON_SOURCE
#else
#define AUDIOCOMMON_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define AUDIOCOMMON_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_msgs {

namespace audio {

/*!
 * @brief This class represents the enumeration SessionType defined by the user
 * in the IDL file.
 * @ingroup AudioCommon
 */
enum SessionType : uint32_t {
  PLAYER_SESSION,
  RECORDER_SESSION,
  LOCALIZER_SESSION,
  CAPTURE_STREAM_SESSION
};
/*!
 * @brief This class represents the enumeration AudioSourceType defined by the
 * user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioSourceType : uint32_t { PCM_FILE, WAV_FILE, PCM_STREAM, MP3_FILE };
/*!
 * @brief This class represents the enumeration AudioPlayerPriority defined by
 * the user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioPlayerPriority : uint32_t {
  PLAYER_PRIORITY_LOW,
  PLAYER_PRIORITY_MEDIUM,
  PLAYER_PRIORITY_HIGH
};
/*!
 * @brief This class represents the enumeration AudioPlayerState defined by the
 * user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioPlayerState : uint32_t {
  PLAYER_IDLE,
  PLAYER_READY,
  PLAYER_PLAYING,
  PLAYER_PAUSED,
  PLAYER_STOPPED,
  PLAYER_COMPLETED,
  PLAYER_ERROR
};
/*!
 * @brief This class represents the enumeration AudioRecorderState defined by
 * the user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioRecorderState : uint32_t {
  RECORDER_IDLE,
  RECORDER_READY,
  RECORDER_RECORDING,
  RECORDER_PAUSED,
  RECORDER_STOPPED,
  RECORDER_ERROR
};
/*!
 * @brief This class represents the enumeration AudioCaptureStreamState defined
 * by the user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioCaptureStreamState : uint32_t {
  CAPTURE_STREAM_IDLE,
  CAPTURE_STREAM_READY,
  CAPTURE_STREAM_STREAMING,
  CAPTURE_STREAM_PAUSED,
  CAPTURE_STREAM_STOPPED,
  CAPTURE_STREAM_ERROR
};
/*!
 * @brief This class represents the enumeration AudioErrorCode defined by the
 * user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioErrorCode : uint32_t {
  SERVICE_DEGRADED,
  INVALID_STATE,
  DEVICE_BUSY,
  NOT_SUPPORTED,
  LOCALIZATION_UNAVAILABLE,
  ALSA_DEVICE_NOT_FOUND,
  ALGO_INIT_FAILED,
  ALGO_PROCESS_FAILED,
  SYSTEM_VOLUME_CTRL_FAILED,
  SYSTEM_MUTE_CTRL_FAILED,
  MEDIA_DECODE_FAILED,
  MEDIA_ENCODE_FAILED,
  MEDIA_FORMAT_UNSUPPORTED
};
/*!
 * @brief This class represents the enumeration AudioEventCode defined by the
 * user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioEventCode : uint32_t {
  PLAYER_INIT_SUCCEEDED,
  PLAYER_START_SUCCEEDED,
  PLAYER_PAUSE_SUCCEEDED,
  PLAYER_STOP_SUCCEEDED,
  PLAYER_RESET_SUCCEEDED,
  PLAYER_DESTROY_SUCCEEDED,
  RECORDER_INIT_SUCCEEDED,
  RECORDER_START_SUCCEEDED,
  RECORDER_PAUSE_SUCCEEDED,
  RECORDER_STOP_SUCCEEDED,
  RECORDER_DESTROY_SUCCEEDED,
  PLAYER_TERMINAL_STATE_CHANGED,
  SYSTEM_VOLUME_SET_SUCCEEDED,
  SYSTEM_MUTE_SET_SUCCEEDED,
  CAPTURE_STREAM_INIT_SUCCEEDED,
  CAPTURE_STREAM_START_SUCCEEDED,
  CAPTURE_STREAM_PAUSE_SUCCEEDED,
  CAPTURE_STREAM_STOP_SUCCEEDED,
  CAPTURE_STREAM_DESTROY_SUCCEEDED
};
/*!
 * @brief This class represents the enumeration AudioErrorCategory defined by
 * the user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioErrorCategory : uint32_t {
  RPC_ERROR,
  PLAYBACK_ERROR,
  RECORD_ERROR,
  CAPTURE_STREAM_RUNTIME_ERROR,
  LOCALIZATION_ERROR,
  SYSTEM_VOLUME_ERROR,
  SYSTEM_MUTE_ERROR,
  INTERNAL_ERROR
};
/*!
 * @brief This class represents the enumeration AudioErrorDetail defined by the
 * user in the IDL file.
 * @ingroup AudioCommon
 */
enum AudioErrorDetail : uint32_t {
  ERROR_DETAIL_NONE,
  ERROR_DETAIL_INIT_PLAYER,
  ERROR_DETAIL_START_PLAYER,
  ERROR_DETAIL_PAUSE_PLAYER,
  ERROR_DETAIL_STOP_PLAYER,
  ERROR_DETAIL_RESET_PLAYER,
  ERROR_DETAIL_DESTROY_PLAYER,
  ERROR_DETAIL_GET_PLAYER_INFO,
  ERROR_DETAIL_SEND_PCM_DATA,
  ERROR_DETAIL_INIT_RECORDER,
  ERROR_DETAIL_START_RECORDER,
  ERROR_DETAIL_PAUSE_RECORDER,
  ERROR_DETAIL_STOP_RECORDER,
  ERROR_DETAIL_DESTROY_RECORDER,
  ERROR_DETAIL_GET_RECORDER_INFO,
  ERROR_DETAIL_GET_DOA_ANGLE,
  ERROR_DETAIL_SET_SYSTEM_VOLUME,
  ERROR_DETAIL_GET_SYSTEM_VOLUME,
  ERROR_DETAIL_SET_SYSTEM_MUTE,
  ERROR_DETAIL_GET_SYSTEM_MUTE,
  ERROR_DETAIL_INIT_CAPTURE_STREAM,
  ERROR_DETAIL_START_CAPTURE_STREAM,
  ERROR_DETAIL_PAUSE_CAPTURE_STREAM,
  ERROR_DETAIL_STOP_CAPTURE_STREAM,
  ERROR_DETAIL_DESTROY_CAPTURE_STREAM,
  ERROR_DETAIL_GET_CAPTURE_STREAM_INFO
};

/*!
 * @brief This class represents the structure RpcMeta defined by the user in the
 * IDL file.
 * @ingroup AudioCommon
 */
class RpcMeta : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_msgs::audio::RpcMeta that will be
   * copied.
   */
  eProsima_user_DllExport RpcMeta(const RpcMeta& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_msgs::audio::RpcMeta that will be
   * copied.
   */
  eProsima_user_DllExport RpcMeta(RpcMeta&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_msgs::audio::RpcMeta that will be
   * copied.
   */
  eProsima_user_DllExport RpcMeta& operator=(const RpcMeta& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_msgs::audio::RpcMeta that will be
   * copied.
   */
  eProsima_user_DllExport RpcMeta& operator=(RpcMeta&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::RpcMeta object to compare.
   */
  eProsima_user_DllExport bool operator==(const RpcMeta& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::RpcMeta object to compare.
   */
  eProsima_user_DllExport bool operator!=(const RpcMeta& x) const;

  /*!
   * @brief This function copies the value in member client_id
   * @param _client_id New value to be copied in member client_id
   */
  eProsima_user_DllExport void client_id(const std::string& _client_id);

  /*!
   * @brief This function moves the value in member client_id
   * @param _client_id New value to be moved in member client_id
   */
  eProsima_user_DllExport void client_id(std::string&& _client_id);

  /*!
   * @brief This function returns a constant reference to member client_id
   * @return Constant reference to member client_id
   */
  eProsima_user_DllExport const std::string& client_id() const;

  /*!
   * @brief This function returns a reference to member client_id
   * @return Reference to member client_id
   */
  eProsima_user_DllExport std::string& client_id();

  /*!
   * @brief This function copies the value in member request_id
   * @param _request_id New value to be copied in member request_id
   */
  eProsima_user_DllExport void request_id(const std::string& _request_id);

  /*!
   * @brief This function moves the value in member request_id
   * @param _request_id New value to be moved in member request_id
   */
  eProsima_user_DllExport void request_id(std::string&& _request_id);

  /*!
   * @brief This function returns a constant reference to member request_id
   * @return Constant reference to member request_id
   */
  eProsima_user_DllExport const std::string& request_id() const;

  /*!
   * @brief This function returns a reference to member request_id
   * @return Reference to member request_id
   */
  eProsima_user_DllExport std::string& request_id();

 private:
  std::string m_client_id;
  std::string m_request_id;

 public:
  typedef RpcMeta type;

  eProsima_user_DllExport RpcMeta();

  eProsima_user_DllExport ~RpcMeta() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace audio

}  // namespace booster_msgs

#endif  // _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOCOMMON_H_
