// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AudioEventTopic.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOEVENTTOPIC_H_
#define _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOEVENTTOPIC_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated AudioEventTopic is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "AudioTopic.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(AUDIOEVENTTOPIC_SOURCE)
#define AUDIOEVENTTOPIC_DllAPI __declspec(dllexport)
#else
#define AUDIOEVENTTOPIC_DllAPI __declspec(dllimport)
#endif  // AUDIOEVENTTOPIC_SOURCE
#else
#define AUDIOEVENTTOPIC_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define AUDIOEVENTTOPIC_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_msgs {

namespace audio {

/*!
 * @brief This class represents the structure AudioEventTopic defined by the
 * user in the IDL file.
 * @ingroup AudioEventTopic
 */
class AudioEventTopic : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_msgs::audio::AudioEventTopic that
   * will be copied.
   */
  eProsima_user_DllExport AudioEventTopic(const AudioEventTopic& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_msgs::audio::AudioEventTopic that
   * will be copied.
   */
  eProsima_user_DllExport AudioEventTopic(AudioEventTopic&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_msgs::audio::AudioEventTopic that
   * will be copied.
   */
  eProsima_user_DllExport AudioEventTopic& operator=(const AudioEventTopic& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_msgs::audio::AudioEventTopic that
   * will be copied.
   */
  eProsima_user_DllExport AudioEventTopic& operator=(
      AudioEventTopic&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::AudioEventTopic object to compare.
   */
  eProsima_user_DllExport bool operator==(const AudioEventTopic& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::AudioEventTopic object to compare.
   */
  eProsima_user_DllExport bool operator!=(const AudioEventTopic& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const booster_msgs::audio::AudioTopicHeader& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(
      booster_msgs::audio::AudioTopicHeader&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const booster_msgs::audio::AudioTopicHeader& header()
      const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport booster_msgs::audio::AudioTopicHeader& header();

  /*!
   * @brief This function sets a value in member event_code
   * @param _event_code New value for member event_code
   */
  eProsima_user_DllExport void event_code(
      booster_msgs::audio::AudioEventCode _event_code);

  /*!
   * @brief This function returns the value of member event_code
   * @return Value of member event_code
   */
  eProsima_user_DllExport booster_msgs::audio::AudioEventCode event_code()
      const;

  /*!
   * @brief This function returns a reference to member event_code
   * @return Reference to member event_code
   */
  eProsima_user_DllExport booster_msgs::audio::AudioEventCode& event_code();

  /*!
   * @brief This function sets a value in member state
   * @param _state New value for member state
   */
  eProsima_user_DllExport void state(int32_t _state);

  /*!
   * @brief This function returns the value of member state
   * @return Value of member state
   */
  eProsima_user_DllExport int32_t state() const;

  /*!
   * @brief This function returns a reference to member state
   * @return Reference to member state
   */
  eProsima_user_DllExport int32_t& state();

  /*!
   * @brief This function copies the value in member detail
   * @param _detail New value to be copied in member detail
   */
  eProsima_user_DllExport void detail(const std::string& _detail);

  /*!
   * @brief This function moves the value in member detail
   * @param _detail New value to be moved in member detail
   */
  eProsima_user_DllExport void detail(std::string&& _detail);

  /*!
   * @brief This function returns a constant reference to member detail
   * @return Constant reference to member detail
   */
  eProsima_user_DllExport const std::string& detail() const;

  /*!
   * @brief This function returns a reference to member detail
   * @return Reference to member detail
   */
  eProsima_user_DllExport std::string& detail();

 private:
  booster_msgs::audio::AudioTopicHeader m_header;
  booster_msgs::audio::AudioEventCode m_event_code{
      booster_msgs::audio::PLAYER_INIT_SUCCEEDED};
  int32_t m_state{0};
  std::string m_detail;

 public:
  typedef AudioEventTopic type;

  eProsima_user_DllExport AudioEventTopic();

  eProsima_user_DllExport ~AudioEventTopic() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace audio

}  // namespace booster_msgs

#endif  // _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOEVENTTOPIC_H_
