// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AudioCaptureFrameTopic.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOCAPTUREFRAMETOPIC_H_
#define _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOCAPTUREFRAMETOPIC_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated AudioCaptureFrameTopic is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "AudioTopic.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(AUDIOCAPTUREFRAMETOPIC_SOURCE)
#define AUDIOCAPTUREFRAMETOPIC_DllAPI __declspec(dllexport)
#else
#define AUDIOCAPTUREFRAMETOPIC_DllAPI __declspec(dllimport)
#endif  // AUDIOCAPTUREFRAMETOPIC_SOURCE
#else
#define AUDIOCAPTUREFRAMETOPIC_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define AUDIOCAPTUREFRAMETOPIC_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_msgs {

namespace audio {

/*!
 * @brief This class represents the structure AudioCaptureFrameTopic defined by
 * the user in the IDL file.
 * @ingroup AudioCaptureFrameTopic
 */
class AudioCaptureFrameTopic : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object
   * booster_msgs::audio::AudioCaptureFrameTopic that will be copied.
   */
  eProsima_user_DllExport AudioCaptureFrameTopic(
      const AudioCaptureFrameTopic& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object
   * booster_msgs::audio::AudioCaptureFrameTopic that will be copied.
   */
  eProsima_user_DllExport AudioCaptureFrameTopic(
      AudioCaptureFrameTopic&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object
   * booster_msgs::audio::AudioCaptureFrameTopic that will be copied.
   */
  eProsima_user_DllExport AudioCaptureFrameTopic& operator=(
      const AudioCaptureFrameTopic& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object
   * booster_msgs::audio::AudioCaptureFrameTopic that will be copied.
   */
  eProsima_user_DllExport AudioCaptureFrameTopic& operator=(
      AudioCaptureFrameTopic&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::AudioCaptureFrameTopic object to compare.
   */
  eProsima_user_DllExport bool operator==(
      const AudioCaptureFrameTopic& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::AudioCaptureFrameTopic object to compare.
   */
  eProsima_user_DllExport bool operator!=(
      const AudioCaptureFrameTopic& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const booster_msgs::audio::AudioTopicHeader& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(
      booster_msgs::audio::AudioTopicHeader&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const booster_msgs::audio::AudioTopicHeader& header()
      const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport booster_msgs::audio::AudioTopicHeader& header();

  /*!
   * @brief This function sets a value in member frame_seq
   * @param _frame_seq New value for member frame_seq
   */
  eProsima_user_DllExport void frame_seq(int64_t _frame_seq);

  /*!
   * @brief This function returns the value of member frame_seq
   * @return Value of member frame_seq
   */
  eProsima_user_DllExport int64_t frame_seq() const;

  /*!
   * @brief This function returns a reference to member frame_seq
   * @return Reference to member frame_seq
   */
  eProsima_user_DllExport int64_t& frame_seq();

  /*!
   * @brief This function sets a value in member raw_valid
   * @param _raw_valid New value for member raw_valid
   */
  eProsima_user_DllExport void raw_valid(bool _raw_valid);

  /*!
   * @brief This function returns the value of member raw_valid
   * @return Value of member raw_valid
   */
  eProsima_user_DllExport bool raw_valid() const;

  /*!
   * @brief This function returns a reference to member raw_valid
   * @return Reference to member raw_valid
   */
  eProsima_user_DllExport bool& raw_valid();

  /*!
   * @brief This function sets a value in member raw_sample_rate_hz
   * @param _raw_sample_rate_hz New value for member raw_sample_rate_hz
   */
  eProsima_user_DllExport void raw_sample_rate_hz(int32_t _raw_sample_rate_hz);

  /*!
   * @brief This function returns the value of member raw_sample_rate_hz
   * @return Value of member raw_sample_rate_hz
   */
  eProsima_user_DllExport int32_t raw_sample_rate_hz() const;

  /*!
   * @brief This function returns a reference to member raw_sample_rate_hz
   * @return Reference to member raw_sample_rate_hz
   */
  eProsima_user_DllExport int32_t& raw_sample_rate_hz();

  /*!
   * @brief This function sets a value in member raw_channels
   * @param _raw_channels New value for member raw_channels
   */
  eProsima_user_DllExport void raw_channels(int32_t _raw_channels);

  /*!
   * @brief This function returns the value of member raw_channels
   * @return Value of member raw_channels
   */
  eProsima_user_DllExport int32_t raw_channels() const;

  /*!
   * @brief This function returns a reference to member raw_channels
   * @return Reference to member raw_channels
   */
  eProsima_user_DllExport int32_t& raw_channels();

  /*!
   * @brief This function sets a value in member raw_bits_per_sample
   * @param _raw_bits_per_sample New value for member raw_bits_per_sample
   */
  eProsima_user_DllExport void raw_bits_per_sample(
      int32_t _raw_bits_per_sample);

  /*!
   * @brief This function returns the value of member raw_bits_per_sample
   * @return Value of member raw_bits_per_sample
   */
  eProsima_user_DllExport int32_t raw_bits_per_sample() const;

  /*!
   * @brief This function returns a reference to member raw_bits_per_sample
   * @return Reference to member raw_bits_per_sample
   */
  eProsima_user_DllExport int32_t& raw_bits_per_sample();

  /*!
   * @brief This function sets a value in member raw_frame_samples_per_channel
   * @param _raw_frame_samples_per_channel New value for member
   * raw_frame_samples_per_channel
   */
  eProsima_user_DllExport void raw_frame_samples_per_channel(
      int32_t _raw_frame_samples_per_channel);

  /*!
   * @brief This function returns the value of member
   * raw_frame_samples_per_channel
   * @return Value of member raw_frame_samples_per_channel
   */
  eProsima_user_DllExport int32_t raw_frame_samples_per_channel() const;

  /*!
   * @brief This function returns a reference to member
   * raw_frame_samples_per_channel
   * @return Reference to member raw_frame_samples_per_channel
   */
  eProsima_user_DllExport int32_t& raw_frame_samples_per_channel();

  /*!
   * @brief This function copies the value in member raw_pcm
   * @param _raw_pcm New value to be copied in member raw_pcm
   */
  eProsima_user_DllExport void raw_pcm(const std::vector<int16_t>& _raw_pcm);

  /*!
   * @brief This function moves the value in member raw_pcm
   * @param _raw_pcm New value to be moved in member raw_pcm
   */
  eProsima_user_DllExport void raw_pcm(std::vector<int16_t>&& _raw_pcm);

  /*!
   * @brief This function returns a constant reference to member raw_pcm
   * @return Constant reference to member raw_pcm
   */
  eProsima_user_DllExport const std::vector<int16_t>& raw_pcm() const;

  /*!
   * @brief This function returns a reference to member raw_pcm
   * @return Reference to member raw_pcm
   */
  eProsima_user_DllExport std::vector<int16_t>& raw_pcm();

  /*!
   * @brief This function sets a value in member naec_valid
   * @param _naec_valid New value for member naec_valid
   */
  eProsima_user_DllExport void naec_valid(bool _naec_valid);

  /*!
   * @brief This function returns the value of member naec_valid
   * @return Value of member naec_valid
   */
  eProsima_user_DllExport bool naec_valid() const;

  /*!
   * @brief This function returns a reference to member naec_valid
   * @return Reference to member naec_valid
   */
  eProsima_user_DllExport bool& naec_valid();

  /*!
   * @brief This function sets a value in member naec_sample_rate_hz
   * @param _naec_sample_rate_hz New value for member naec_sample_rate_hz
   */
  eProsima_user_DllExport void naec_sample_rate_hz(
      int32_t _naec_sample_rate_hz);

  /*!
   * @brief This function returns the value of member naec_sample_rate_hz
   * @return Value of member naec_sample_rate_hz
   */
  eProsima_user_DllExport int32_t naec_sample_rate_hz() const;

  /*!
   * @brief This function returns a reference to member naec_sample_rate_hz
   * @return Reference to member naec_sample_rate_hz
   */
  eProsima_user_DllExport int32_t& naec_sample_rate_hz();

  /*!
   * @brief This function sets a value in member naec_channels
   * @param _naec_channels New value for member naec_channels
   */
  eProsima_user_DllExport void naec_channels(int32_t _naec_channels);

  /*!
   * @brief This function returns the value of member naec_channels
   * @return Value of member naec_channels
   */
  eProsima_user_DllExport int32_t naec_channels() const;

  /*!
   * @brief This function returns a reference to member naec_channels
   * @return Reference to member naec_channels
   */
  eProsima_user_DllExport int32_t& naec_channels();

  /*!
   * @brief This function sets a value in member naec_bits_per_sample
   * @param _naec_bits_per_sample New value for member naec_bits_per_sample
   */
  eProsima_user_DllExport void naec_bits_per_sample(
      int32_t _naec_bits_per_sample);

  /*!
   * @brief This function returns the value of member naec_bits_per_sample
   * @return Value of member naec_bits_per_sample
   */
  eProsima_user_DllExport int32_t naec_bits_per_sample() const;

  /*!
   * @brief This function returns a reference to member naec_bits_per_sample
   * @return Reference to member naec_bits_per_sample
   */
  eProsima_user_DllExport int32_t& naec_bits_per_sample();

  /*!
   * @brief This function sets a value in member naec_frame_samples_per_channel
   * @param _naec_frame_samples_per_channel New value for member
   * naec_frame_samples_per_channel
   */
  eProsima_user_DllExport void naec_frame_samples_per_channel(
      int32_t _naec_frame_samples_per_channel);

  /*!
   * @brief This function returns the value of member
   * naec_frame_samples_per_channel
   * @return Value of member naec_frame_samples_per_channel
   */
  eProsima_user_DllExport int32_t naec_frame_samples_per_channel() const;

  /*!
   * @brief This function returns a reference to member
   * naec_frame_samples_per_channel
   * @return Reference to member naec_frame_samples_per_channel
   */
  eProsima_user_DllExport int32_t& naec_frame_samples_per_channel();

  /*!
   * @brief This function copies the value in member naec_pcm
   * @param _naec_pcm New value to be copied in member naec_pcm
   */
  eProsima_user_DllExport void naec_pcm(const std::vector<int16_t>& _naec_pcm);

  /*!
   * @brief This function moves the value in member naec_pcm
   * @param _naec_pcm New value to be moved in member naec_pcm
   */
  eProsima_user_DllExport void naec_pcm(std::vector<int16_t>&& _naec_pcm);

  /*!
   * @brief This function returns a constant reference to member naec_pcm
   * @return Constant reference to member naec_pcm
   */
  eProsima_user_DllExport const std::vector<int16_t>& naec_pcm() const;

  /*!
   * @brief This function returns a reference to member naec_pcm
   * @return Reference to member naec_pcm
   */
  eProsima_user_DllExport std::vector<int16_t>& naec_pcm();

 private:
  booster_msgs::audio::AudioTopicHeader m_header;
  int64_t m_frame_seq{0};
  bool m_raw_valid{false};
  int32_t m_raw_sample_rate_hz{0};
  int32_t m_raw_channels{0};
  int32_t m_raw_bits_per_sample{0};
  int32_t m_raw_frame_samples_per_channel{0};
  std::vector<int16_t> m_raw_pcm;
  bool m_naec_valid{false};
  int32_t m_naec_sample_rate_hz{0};
  int32_t m_naec_channels{0};
  int32_t m_naec_bits_per_sample{0};
  int32_t m_naec_frame_samples_per_channel{0};
  std::vector<int16_t> m_naec_pcm;

 public:
  typedef AudioCaptureFrameTopic type;

  eProsima_user_DllExport AudioCaptureFrameTopic();

  eProsima_user_DllExport ~AudioCaptureFrameTopic() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace audio

}  // namespace booster_msgs

#endif  // _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_AUDIOCAPTUREFRAMETOPIC_H_
