// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file InitPlayerRequest.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_INITPLAYERREQUEST_H_
#define _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_INITPLAYERREQUEST_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated InitPlayerRequest is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "AudioCommon.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(INITPLAYERREQUEST_SOURCE)
#define INITPLAYERREQUEST_DllAPI __declspec(dllexport)
#else
#define INITPLAYERREQUEST_DllAPI __declspec(dllimport)
#endif  // INITPLAYERREQUEST_SOURCE
#else
#define INITPLAYERREQUEST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define INITPLAYERREQUEST_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_msgs {

namespace audio {

/*!
 * @brief This class represents the structure InitPlayerRequest defined by the
 * user in the IDL file.
 * @ingroup InitPlayerRequest
 */
class InitPlayerRequest : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_msgs::audio::InitPlayerRequest
   * that will be copied.
   */
  eProsima_user_DllExport InitPlayerRequest(const InitPlayerRequest& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_msgs::audio::InitPlayerRequest
   * that will be copied.
   */
  eProsima_user_DllExport InitPlayerRequest(InitPlayerRequest&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_msgs::audio::InitPlayerRequest
   * that will be copied.
   */
  eProsima_user_DllExport InitPlayerRequest& operator=(
      const InitPlayerRequest& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_msgs::audio::InitPlayerRequest
   * that will be copied.
   */
  eProsima_user_DllExport InitPlayerRequest& operator=(
      InitPlayerRequest&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::InitPlayerRequest object to compare.
   */
  eProsima_user_DllExport bool operator==(const InitPlayerRequest& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::InitPlayerRequest object to compare.
   */
  eProsima_user_DllExport bool operator!=(const InitPlayerRequest& x) const;

  /*!
   * @brief This function copies the value in member client_id
   * @param _client_id New value to be copied in member client_id
   */
  eProsima_user_DllExport void client_id(const std::string& _client_id);

  /*!
   * @brief This function moves the value in member client_id
   * @param _client_id New value to be moved in member client_id
   */
  eProsima_user_DllExport void client_id(std::string&& _client_id);

  /*!
   * @brief This function returns a constant reference to member client_id
   * @return Constant reference to member client_id
   */
  eProsima_user_DllExport const std::string& client_id() const;

  /*!
   * @brief This function returns a reference to member client_id
   * @return Reference to member client_id
   */
  eProsima_user_DllExport std::string& client_id();

  /*!
   * @brief This function copies the value in member request_id
   * @param _request_id New value to be copied in member request_id
   */
  eProsima_user_DllExport void request_id(const std::string& _request_id);

  /*!
   * @brief This function moves the value in member request_id
   * @param _request_id New value to be moved in member request_id
   */
  eProsima_user_DllExport void request_id(std::string&& _request_id);

  /*!
   * @brief This function returns a constant reference to member request_id
   * @return Constant reference to member request_id
   */
  eProsima_user_DllExport const std::string& request_id() const;

  /*!
   * @brief This function returns a reference to member request_id
   * @return Reference to member request_id
   */
  eProsima_user_DllExport std::string& request_id();

  /*!
   * @brief This function sets a value in member source_type
   * @param _source_type New value for member source_type
   */
  eProsima_user_DllExport void source_type(
      booster_msgs::audio::AudioSourceType _source_type);

  /*!
   * @brief This function returns the value of member source_type
   * @return Value of member source_type
   */
  eProsima_user_DllExport booster_msgs::audio::AudioSourceType source_type()
      const;

  /*!
   * @brief This function returns a reference to member source_type
   * @return Reference to member source_type
   */
  eProsima_user_DllExport booster_msgs::audio::AudioSourceType& source_type();

  /*!
   * @brief This function copies the value in member source_uri
   * @param _source_uri New value to be copied in member source_uri
   */
  eProsima_user_DllExport void source_uri(const std::string& _source_uri);

  /*!
   * @brief This function moves the value in member source_uri
   * @param _source_uri New value to be moved in member source_uri
   */
  eProsima_user_DllExport void source_uri(std::string&& _source_uri);

  /*!
   * @brief This function returns a constant reference to member source_uri
   * @return Constant reference to member source_uri
   */
  eProsima_user_DllExport const std::string& source_uri() const;

  /*!
   * @brief This function returns a reference to member source_uri
   * @return Reference to member source_uri
   */
  eProsima_user_DllExport std::string& source_uri();

  /*!
   * @brief This function sets a value in member sample_rate_hz
   * @param _sample_rate_hz New value for member sample_rate_hz
   */
  eProsima_user_DllExport void sample_rate_hz(int32_t _sample_rate_hz);

  /*!
   * @brief This function returns the value of member sample_rate_hz
   * @return Value of member sample_rate_hz
   */
  eProsima_user_DllExport int32_t sample_rate_hz() const;

  /*!
   * @brief This function returns a reference to member sample_rate_hz
   * @return Reference to member sample_rate_hz
   */
  eProsima_user_DllExport int32_t& sample_rate_hz();

  /*!
   * @brief This function sets a value in member channels
   * @param _channels New value for member channels
   */
  eProsima_user_DllExport void channels(int32_t _channels);

  /*!
   * @brief This function returns the value of member channels
   * @return Value of member channels
   */
  eProsima_user_DllExport int32_t channels() const;

  /*!
   * @brief This function returns a reference to member channels
   * @return Reference to member channels
   */
  eProsima_user_DllExport int32_t& channels();

  /*!
   * @brief This function sets a value in member bits_per_sample
   * @param _bits_per_sample New value for member bits_per_sample
   */
  eProsima_user_DllExport void bits_per_sample(int32_t _bits_per_sample);

  /*!
   * @brief This function returns the value of member bits_per_sample
   * @return Value of member bits_per_sample
   */
  eProsima_user_DllExport int32_t bits_per_sample() const;

  /*!
   * @brief This function returns a reference to member bits_per_sample
   * @return Reference to member bits_per_sample
   */
  eProsima_user_DllExport int32_t& bits_per_sample();

  /*!
   * @brief This function sets a value in member priority
   * @param _priority New value for member priority
   */
  eProsima_user_DllExport void priority(
      booster_msgs::audio::AudioPlayerPriority _priority);

  /*!
   * @brief This function returns the value of member priority
   * @return Value of member priority
   */
  eProsima_user_DllExport booster_msgs::audio::AudioPlayerPriority priority()
      const;

  /*!
   * @brief This function returns a reference to member priority
   * @return Reference to member priority
   */
  eProsima_user_DllExport booster_msgs::audio::AudioPlayerPriority& priority();

 private:
  std::string m_client_id;
  std::string m_request_id;
  booster_msgs::audio::AudioSourceType m_source_type{
      booster_msgs::audio::PCM_FILE};
  std::string m_source_uri;
  int32_t m_sample_rate_hz{0};
  int32_t m_channels{0};
  int32_t m_bits_per_sample{0};
  booster_msgs::audio::AudioPlayerPriority m_priority{
      booster_msgs::audio::PLAYER_PRIORITY_LOW};

 public:
  typedef InitPlayerRequest type;

  eProsima_user_DllExport InitPlayerRequest();

  eProsima_user_DllExport ~InitPlayerRequest() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace audio

}  // namespace booster_msgs

#endif  // _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_INITPLAYERREQUEST_H_
