// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PlayerInfoResponse.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_PLAYERINFORESPONSE_H_
#define _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_PLAYERINFORESPONSE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated PlayerInfoResponse is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "AudioCommon.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PLAYERINFORESPONSE_SOURCE)
#define PLAYERINFORESPONSE_DllAPI __declspec(dllexport)
#else
#define PLAYERINFORESPONSE_DllAPI __declspec(dllimport)
#endif  // PLAYERINFORESPONSE_SOURCE
#else
#define PLAYERINFORESPONSE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PLAYERINFORESPONSE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_msgs {

namespace audio {

/*!
 * @brief This class represents the structure PlayerInfoResponse defined by the
 * user in the IDL file.
 * @ingroup PlayerInfoResponse
 */
class PlayerInfoResponse : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_msgs::audio::PlayerInfoResponse
   * that will be copied.
   */
  eProsima_user_DllExport PlayerInfoResponse(const PlayerInfoResponse& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_msgs::audio::PlayerInfoResponse
   * that will be copied.
   */
  eProsima_user_DllExport PlayerInfoResponse(PlayerInfoResponse&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_msgs::audio::PlayerInfoResponse
   * that will be copied.
   */
  eProsima_user_DllExport PlayerInfoResponse& operator=(
      const PlayerInfoResponse& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_msgs::audio::PlayerInfoResponse
   * that will be copied.
   */
  eProsima_user_DllExport PlayerInfoResponse& operator=(
      PlayerInfoResponse&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::PlayerInfoResponse object to compare.
   */
  eProsima_user_DllExport bool operator==(const PlayerInfoResponse& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::PlayerInfoResponse object to compare.
   */
  eProsima_user_DllExport bool operator!=(const PlayerInfoResponse& x) const;

  /*!
   * @brief This function sets a value in member ret_code
   * @param _ret_code New value for member ret_code
   */
  eProsima_user_DllExport void ret_code(int32_t _ret_code);

  /*!
   * @brief This function returns the value of member ret_code
   * @return Value of member ret_code
   */
  eProsima_user_DllExport int32_t ret_code() const;

  /*!
   * @brief This function returns a reference to member ret_code
   * @return Reference to member ret_code
   */
  eProsima_user_DllExport int32_t& ret_code();

  /*!
   * @brief This function copies the value in member ret_msg
   * @param _ret_msg New value to be copied in member ret_msg
   */
  eProsima_user_DllExport void ret_msg(const std::string& _ret_msg);

  /*!
   * @brief This function moves the value in member ret_msg
   * @param _ret_msg New value to be moved in member ret_msg
   */
  eProsima_user_DllExport void ret_msg(std::string&& _ret_msg);

  /*!
   * @brief This function returns a constant reference to member ret_msg
   * @return Constant reference to member ret_msg
   */
  eProsima_user_DllExport const std::string& ret_msg() const;

  /*!
   * @brief This function returns a reference to member ret_msg
   * @return Reference to member ret_msg
   */
  eProsima_user_DllExport std::string& ret_msg();

  /*!
   * @brief This function sets a value in member state
   * @param _state New value for member state
   */
  eProsima_user_DllExport void state(
      booster_msgs::audio::AudioPlayerState _state);

  /*!
   * @brief This function returns the value of member state
   * @return Value of member state
   */
  eProsima_user_DllExport booster_msgs::audio::AudioPlayerState state() const;

  /*!
   * @brief This function returns a reference to member state
   * @return Reference to member state
   */
  eProsima_user_DllExport booster_msgs::audio::AudioPlayerState& state();

  /*!
   * @brief This function sets a value in member played_bytes
   * @param _played_bytes New value for member played_bytes
   */
  eProsima_user_DllExport void played_bytes(int64_t _played_bytes);

  /*!
   * @brief This function returns the value of member played_bytes
   * @return Value of member played_bytes
   */
  eProsima_user_DllExport int64_t played_bytes() const;

  /*!
   * @brief This function returns a reference to member played_bytes
   * @return Reference to member played_bytes
   */
  eProsima_user_DllExport int64_t& played_bytes();

  /*!
   * @brief This function sets a value in member total_bytes
   * @param _total_bytes New value for member total_bytes
   */
  eProsima_user_DllExport void total_bytes(int64_t _total_bytes);

  /*!
   * @brief This function returns the value of member total_bytes
   * @return Value of member total_bytes
   */
  eProsima_user_DllExport int64_t total_bytes() const;

  /*!
   * @brief This function returns a reference to member total_bytes
   * @return Reference to member total_bytes
   */
  eProsima_user_DllExport int64_t& total_bytes();

  /*!
   * @brief This function sets a value in member volume
   * @param _volume New value for member volume
   */
  eProsima_user_DllExport void volume(float _volume);

  /*!
   * @brief This function returns the value of member volume
   * @return Value of member volume
   */
  eProsima_user_DllExport float volume() const;

  /*!
   * @brief This function returns a reference to member volume
   * @return Reference to member volume
   */
  eProsima_user_DllExport float& volume();

 private:
  int32_t m_ret_code{0};
  std::string m_ret_msg;
  booster_msgs::audio::AudioPlayerState m_state{
      booster_msgs::audio::PLAYER_IDLE};
  int64_t m_played_bytes{0};
  int64_t m_total_bytes{0};
  float m_volume{0.0};

 public:
  typedef PlayerInfoResponse type;

  eProsima_user_DllExport PlayerInfoResponse();

  eProsima_user_DllExport ~PlayerInfoResponse() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace audio

}  // namespace booster_msgs

#endif  // _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_PLAYERINFORESPONSE_H_
